Document guide for H.264
tiny-pilot/ustreamer pull request #2
Opened 2022-04-05 17:09 UTC by jotaen4tinypilot

Resolves https://github.com/tiny-pilot/ustreamer/issues/1.

As of 2022-04-05 it’s WIP, but I think the basic structure would be sensible as proposed here.

- On a high-level, I wanted to divide the document into 4 sections: 1) a quick primer on the motivation, 2) a high-level overview of the involved components and how they play together, 3) the backend setup (not started yet), 4) the frontend setup.
- The HTML page is functional. I think it makes sense to keep the JS commentary relatively minimal, and provide the context in a separate description.
  - Instead of having a single code blob, we could split it up into separate code fragments. The would allow us to put the explanations next to the code. However, it makes it harder to see it all together then. For my taste, the single code blob would still be small and straightforward enough, also considering that we have described everything beforehand.
- I’m not sure what the best way is to provide the JS libraries. I’ve just linked to the respective Github projects, but it’s still up to the user to find them there. I’d suppose this might be okay, though, since the audience are developers themselves, so they should know how to find a library.
- I haven’t figured out how to stop the video stream yet. I.e., I’m able to successfully send a `stop` request to the Janus plugin, but that doesn’t stop the media stream. So for making the start/stop functionality happen, I need to look into this more.
- I have stumbled across [the solution to fix the cold start behaviour](https://github.com/tiny-pilot/tinypilot/issues/948#issuecomment-1087923465), which is checking for the `503` error code and then retrying. (The retry should probably be throttled, though.)

@mtlynch a few questions before I move on:

- How much do we want to go into detail about the WebRTC protocol in general? Shall we assume that people are sufficiently familiar with it, or shall we provide more context around the control flow? (E.g., protocol/codec negotiation; signalling, etc.) We could add this as another section then, for example. This is basically all abstracted away by the client library, though, so it would be mostly for context.
- Currently, the guide covers the essentials for making a “Hello World” happen. Is that enough, or do you think we should go deeper with the explanations?

@jdeanwallace would you have time for a quick video call (e.g. this week) to briefly walk me through the backend setup and compilation? I think I have an overview of the involved steps and pieces, but it’s not clear enough yet for me to be able to write it up.

2022-04-06 13:54 UTC, jdeanwallace reviewed
@jotaen4tinypilot Yeah sure, I'll email you a doodle to schedule a time.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-Mzz8YSw7h5cq4pes3fU:b80onpp)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-04-06 19:46 UTC, mtlynch requested changes
Cool, this is pretty in line with what I had in mind. I have some notes, but I think we're headed in the right direction.

>I haven’t figured out how to stop the video stream yet. I.e., I’m able to successfully send a stop request to the Janus plugin, but that doesn’t stop the media stream. So for making the start/stop functionality happen, I need to look into this more.

Can you clarify what happens when you send the stop request? Are you saying Janus continues streaming media to the JS client? Or that uStreamer continues streaming media to Janus?

>How much do we want to go into detail about the WebRTC protocol in general? Shall we assume that people are sufficiently familiar with it, or shall we provide more context around the control flow? (E.g., protocol/codec negotiation; signalling, etc.) We could add this as another section then, for example. This is basically all abstracted away by the client library, though, so it would be mostly for context.

I think the level of detail we have now is good. 

 don't want to go into more detail on WebRTC. The goal is just for the reader to understand how to interact with Janus/uStreamer over WebRTC, but we're not trying to teach them the details of the WebRTC protocol in this document.

The only thing I'd add is an explanation of what JSEP messages are, but just briefly (1-2 sentences).

>Currently, the guide covers the essentials for making a “Hello World” happen. Is that enough, or do you think we should go deeper with the explanations?

Yep, hello world is fine.

>The HTML page is functional. I think it makes sense to keep the JS commentary relatively minimal, and provide the context in a separate description.
>Instead of having a single code blob, we could split it up into separate code fragments. The would allow us to put the explanations next to the code. However, it makes it harder to see it all together then. For my taste, the single code blob would still be small and straightforward enough, also considering that we have described everything beforehand.

I like having it in one complete chunk, but I think we should go heavier on the code comments.

Right now it's commented kind of at the level of production code, but I think we should have comments walking the reader through what everything means.

We don't have to teach the reader JavaScript, so like we don't need a comment for this line (`let janusPluginHandle = null;`). But for `error: console.error,`, I think it's worth having a comment to explain what that means. Ditto for almost every line or function that interacts with Janus.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-MzzhW7F-CLnQ0KJRhsH:b-ivjn21)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 1 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--F2tM4S_0q8IWxGDV:-N--F2tM4S_0q8IWxGDW:b-bs0sdx) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L1)):*
I think we can communicate the purpose of the document a little earlier. Suggest something like:

># Streaming H.264 video over WebRTC

>uStreamer supports bandwidth-efficient streaming using H.264 compression and the Janus WebRTC server. This guide explains how to configure uStreamer to stream with H264+WebRTC and how to consume that stream within a web application.
___
*[docs/h264.md, line 3 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--GZGM7731_aHIDGlL:-N--GZGM7731_aHIDGlM:bqo0s0q) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L3)):*
> ```Markdown
> # Guide to H.264 streaming
> 
> By default, µStreamer outputs an [MJPEG stream](https://en.wikipedia.org/wiki/Motion_JPEG). MJPEG is a continuous series of single JPEG images which are “emitted” at a specific rate. While this is a relatively simple mechanism, it can also consume a lot of bandwidth.
> ```

We don't need to explain MJPEG.
___
*[docs/h264.md, line 19 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--HOGB6lDIlZ2BFwxH:-N--HOGB6lDIlZ2BFwxI:bnhbjqy) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L19)):*
Can we make it more explicit who's performing what action? This is a pattern we're repeating a lot in the document where we say "X happens" but we're unclear about who's initiating the action and in some cases who's receiving the action.

For difficult technical content, I think it's better to be overly explicit even if it sounds repetitive, so like:

>1. Server starts the uStreamer service.
>2. Server starts the Janus WebRTC service with the uStreamer plugin.
>3. Client-side JavaScript application establishes a connection to the Janus server.
>4. Client-side JavaScript application instructs Janus server to attach the uStreamer plugin and start the video stream.

(ditto throughout)
___
*[docs/h264.md, line 28 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzlNIHC52_H3V85wsn:-MzzlNIHC52_H3V85wso:b-obz4b1) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L28)):*
> ```Markdown
> TODO:
> - Install µStreamer and Janus
>   + Install required packages
> ```

We can assume the reader has installed the dependencies already from the main uStreamer README.
___
*[docs/h264.md, line 29 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-Mzzkstm82d3fOTMM9UR:-Mzzkstm82d3fOTMM9US:by3j2qi) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L29)):*
> ```Markdown
> - Install µStreamer and Janus
>   + Install required packages
>   + Compile Janus
> ```

I'd like us to just point the reader to the Janus install instructions:

https://github.com/meetecho/janus-gateway

They're not very good, but I don't want to clutter these docs with the whole explanation of how to compile Janus.
___
*[docs/h264.md, line 39 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzkgZmA-Q-uyGt0lOi:-MzzkgZmA-Q-uyGt0lOj:bx6plmz) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L39)):*
> ```Markdown
> 
> - [The WebRTC Adapter library](https://github.com/webrtchacks/adapter) (`webrtc-adapter.js`, version `8.1.1`)
> - [The JavaScript library of Janus Gateway](https://github.com/meetecho/janus-gateway) (`janus.js`, version `1.0.0`)
> ```

Can we tell them to just download from here:

https://raw.githubusercontent.com/meetecho/janus-gateway/v1.0.0/html/janus.js
___
*[docs/h264.md, line 51 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--GuNF3xqwUk2HcDgi:-N--GuNF3xqwUk2HcDgj:b-8iqr76) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L51)):*
> ```Markdown
>    - `onmessage` callback for general messages
>    - `onremotetrack` for the video stream
> 1. Send a `watch` request to the µStreamer plugin. This initiates the H.264 stream in the plugin itself. For the very first call after starting the plugin, this doesn’t immediately succeed. It takes a few seconds until the stream becomes available. Therefore, we have to retry the request, until the plugin indicates that it’s ready. It does that by generating a JSEP offer, obtained via the `jsepOffer` parameter in the `onmessage` callback.
> ```

Can we define a "JSEP offer" in a section above?
___
*[docs/h264.md, line 61 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzkQD00Mw7_DA8t-xM:-MzzkQD00Mw7_DA8t-xN:bfp7bat) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L61)):*
> ```Markdown
>   <meta charset="utf-8">
>   <title>µStreamer H.264 demo</title>
>   <script src="webrtc-adapter.js"></script>
> ```

Can we make this `<script src="https://webrtc.github.io/adapter/adapter-8.1.0.js"></script>` for simplicity? That's one less thing for the user to download and  [...]

2022-04-07 18:08 UTC, jotaen4tinypilot commented
I’ve pushed some updates, but I’m not completely done yet. Still ongoing:

- Jason walked me through the backend bits today, which helped a lot, but I still need to finish writing that up.
- The start/stop functionality is not demonstrated yet.

2022-04-08 10:43 UTC, jotaen4tinypilot reviewed
For convenience, here is the latest rendered preview: https://github.com/tiny-pilot/ustreamer/blob/h264-guide/docs/h264.md

> I think we should have comments walking the reader through what everything means.

Done.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-3pqJxC2RbCxyDUkl_:b-20patf)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 1 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--F2tM4S_0q8IWxGDV:-N-3RVYx7s5n6kNlGB9O:b-jhz6q6) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L1)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I think we can communicate the purpose of the document a little earlier. Suggest something like:

># Streaming H.264 video over WebRTC

>uStreamer supports bandwidth-efficient streaming using H.264 compression and the Janus WebRTC server. This guide explains how to configure uStreamer to stream with H264+WebRTC and how to consume that stream within a web application.




</blockquote></details>

Thanks, that reads well. Done.
___
*[docs/h264.md, line 3 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--GZGM7731_aHIDGlL:-N-3RWiH6x0-8VUv8meF:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L3)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

We don't need to explain MJPEG.
</blockquote></details>

Done.
___
*[docs/h264.md, line 19 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--HOGB6lDIlZ2BFwxH:-N-4BrGb9wc7Nji9zvt9:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L19)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we make it more explicit who's performing what action? This is a pattern we're repeating a lot in the document where we say "X happens" but we're unclear about who's initiating the action and in some cases who's receiving the action.

For difficult technical content, I think it's better to be overly explicit even if it sounds repetitive, so like:

>1. Server starts the uStreamer service.
>2. Server starts the Janus WebRTC service with the uStreamer plugin.
>3. Client-side JavaScript application establishes a connection to the Janus server.
>4. Client-side JavaScript application instructs Janus server to attach the uStreamer plugin and start the video stream.

(ditto throughout)
</blockquote></details>

Done.
___
*[docs/h264.md, line 28 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzlNIHC52_H3V85wsn:-N-3X5ZH4TbnUi5veTkU:b14qjgr) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L28)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

We can assume the reader has installed the dependencies already from the main uStreamer README.
</blockquote></details>

:+1: Done.
___
*[docs/h264.md, line 29 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-Mzzkstm82d3fOTMM9UR:-N-3XPde6K_BnrV9g8og:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L29)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I'd like us to just point the reader to the Janus install instructions:

https://github.com/meetecho/janus-gateway

They're not very good, but I don't want to clutter these docs with the whole explanation of how to compile Janus.
</blockquote></details>

Done.
___
*[docs/h264.md, line 39 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzkgZmA-Q-uyGt0lOi:-N-3TpHX0D5diknPZ2rM:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L39)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we tell them to just download from here:

https://raw.githubusercontent.com/meetecho/janus-gateway/v1.0.0/html/janus.js
</blockquote></details>

Done.
___
*[docs/h264.md, line 51 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--GuNF3xqwUk2HcDgi:-N-3tEhz5n08E3gkjcvy:b-4hbrux) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L51)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we define a "JSEP offer" in a section above?
</blockquote></details>

Done. It somehow felt strange to me to have the explanation separate: it seems quite prominent then, but actually the JSEP exchange is a relatively “irrelevant” implementation detail. (At least irrelevant to our example, because it’s completely handled by the library.)

I’ve tried to inline it now, to indicate what it’s there for.
___
*[docs/h264.md, line 61 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-MzzkQD00Mw7_DA8t-xM:-N-3TwVN4lEqbkbG6wB5:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L61)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we make this `<script src="https://webrtc.github.io/adapter/adapter-8.1.0.js"></script>` for simplicity? That's one less thing for the user to download and put in the right place.

For some reason 8.1.1 is not published yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 10:44 UTC, jotaen4tinypilot commented
@jdeanwallace could you have look over the “Server Setup” section?

2022-04-08 10:45 UTC, jotaen4tinypilot commented on docs/h264.md
> +      server: 'ws://raspberrypi/janus/ws',
Not sure `raspberrypi` is the most sensible default hostname here 🤔

2022-04-08 12:52 UTC, jdeanwallace reviewed
@jotaen4tinypilot Looks good, I've made a few comments. One nit-picky thing that bothers me the how we refer to the uStreamer Janus plugin. Which is more correct:
1. uStreamer Janus plugin
2. Janus uStreamer plugin
I initially prefered (1) because it ends in "Janus plugin" i.e. a plugin that is installed into Janus. However, the [Janus website prefers (2)](https://janus.conf.meetecho.com/docs/group__plugins.html#files).

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-8C1_6160qMB4pY006:b-ezgean)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 16 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-87RJ11KBSM1TMTkOy:-N-87RJ11KBSM1TMTkOz:bnajpru) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L16)):*
> ```Markdown
> 
> 1. The server starts the µStreamer service.
> 1. The server starts the Janus WebRTC server with the µStreamer plugin.
> ```

(nit, optional) We're using "server" to refer to both the hardware and software. Which is correct, but might be ambiguous.

Suggestion:
The server starts the Janus WebRTC *service* with the µStreamer plugin.

This might not work everywhere in this document.
___
*[docs/h264.md, line 26 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8-3ENE-PtohKcCTLt:-N-8-3ENE-PtohKcCTLu:bbooxd4) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L26)):*
Can we pin this to a specific version of uStreamer (i.e. `v4.13`)? The newest version of [uStreamer doesn't seem to use `WITH_OMX` anymore](https://github.com/pikvm/ustreamer/tree/v5.3#usage):
> For M2M hardware encoding on Raspberry Pi, you need at least 5.15.32 kernel. OpenMAX and MMAL support on older kernels is deprecated and removed.

We've tracking this change with: https://github.com/tiny-pilot/ansible-role-ustreamer/issues/58
___
*[docs/h264.md, line 27 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8AdySAOn287N9knwk:-N-8AdySAOn287N9knwl:b6eqk9v) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L27)):*
> ```Markdown
> 
> - The system packages that µStreamer depends on; see [µStreamer documentation](https://github.com/pikvm/ustreamer).
> - The Janus WebRTC server, with WebSocket transport enabled; see [Janus documentation](https://github.com/meetecho/janus-gateway).
> ```

(no action required) As we discussed before, this step is deceivingly tricky, but technically not our problem. Linking to a handy install script would be super helpful.
___
*[docs/h264.md, line 31 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-819EV5AZps7j_gao2:-N-819EV5AZps7j_gao3:bjfj55w) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L31)):*
(nit) It's true that `WITH_OMX` is required to enable the h264 shared memory sink, but that's not what the `WITH_OMX` flag was solely created for.

Suggestion:
> and enable hardware encoding with OpenMAX to support memory sharing (`WITH_OMX`).
___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-89kXP1vmniAj_8hgJ:bz1wnrr) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
> ```Markdown
> git clone --depth=1 https://github.com/pikvm/ustreamer
> cd ustreamer
> make WITH_OMX=1 WITH_JANUS=1
> ```

The user will probably run into this bug: https://github.com/tiny-pilot/ansible-role-tinypilot/issues/192

Can we mention here it in case uStreamer fails to compile?
___
*[docs/h264.md, line 128 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-Mzuh40VvOB7o4WnEeB2-r3-128:-N-84lM54rYQMOp5YrQH:bybjv4n) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L128)):*
<details><summary><i>Previously, jotaen4tinypilot wrote…</i></summary><blockquote>

Not sure `raspberrypi` is the most sensible default hostname here 🤔 
</blockquote></details>

In this case, we're not using a reverse proxy like nginx, so this can either be
```javascript
"ws://127.0.0.1:8188/";
// or
"ws://" + window.location.hostname + ":8188/";
```
depending on how the demo html file is accessed.
([source](https://janus.conf.meetecho.com/docs/deploy.html#deplyws))


<!-- Sent from Reviewable.io -->

2022-04-08 13:03 UTC, mtlynch reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 26 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8-3ENE-PtohKcCTLt:-N-8FDEyCTUECsjGgU_t:b-80uh3n) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L26)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

Can we pin this to a specific version of uStreamer (i.e. `v4.13`)? The newest version of [uStreamer doesn't seem to use `WITH_OMX` anymore](https://github.com/pikvm/ustreamer/tree/v5.3#usage):
> For M2M hardware encoding on Raspberry Pi, you need at least 5.15.32 kernel. OpenMAX and MMAL support on older kernels is deprecated and removed.

We've tracking this change with: https://github.com/tiny-pilot/ansible-role-ustreamer/issues/58
</blockquote></details>

If this were a separate blog post, I'd say pin it, but this documentation is meant to live with uStreamer, so it should always work with uStreamer's `master`.

I think we should stick with the `master` branch and drop `WITH_OMX=1`, since that's gone as of uStreamer 5.x.

I don't think we need a make flag to support memory sharing anymore, but we should verify that with the latest uStreamer and Pi kernel (you'll need to run `sudo rpi-update` to get a kernel compatible with uStreamer 5.x).


<!-- Sent from Reviewable.io -->

2022-04-08 16:40 UTC, mtlynch requested changes
Good revisions! I think the inline code comments help a lot.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-91qcBBvEZc4LU1zMT:bz8imrs)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 51 at r1](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N--GuNF3xqwUk2HcDgi:-N-8zPfl9-EmggN5gJUV:b-mluy8r) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/3f39775dce0153034fb766071ded92ea8b8cd28d/docs/h264.md#L51)):*
<details><summary><i>Previously, jotaen4tinypilot wrote…</i></summary><blockquote>

Done. It somehow felt strange to me to have the explanation separate: it seems quite prominent then, but actually the JSEP exchange is a relatively “irrelevant” implementation detail. (At least irrelevant to our example, because it’s completely handled by the library.)

I’ve tried to inline it now, to indicate what it’s there for.
</blockquote></details>

Oh, yeah, I thought it was more complicated, so inline is good.
___
*[docs/h264.md, line 26 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8wWi19Y9EEy0Rdh3K:-N-8wWi19Y9EEy0Rdh3L:b-g4hhi8) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L26)):*
> ```Markdown
> The following prerequisites need to be installed on the server:
> 
> - The system packages that µStreamer depends on; see [µStreamer documentation](https://github.com/pikvm/ustreamer).
> ```

Can we link to the specific section with a relative link, like:

```markdown
see the [build instructions](../README.md#building).
```
___
*[docs/h264.md, line 27 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8AdySAOn287N9knwk:-N-8zrQLB51Gwiwi87Ve:b-pz1evt) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L27)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

(no action required) As we discussed before, this step is deceivingly tricky, but technically not our problem. Linking to a handy install script would be super helpful.
</blockquote></details>

I don't think there's a good solution here. There isn't a good install script. If we make one, it will go out of date pretty quickly.
___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-8xCtvEvz4L9CQHsXG:b-qop28a) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

The user will probably run into this bug: https://github.com/tiny-pilot/ansible-role-tinypilot/issues/192

Can we mention here it in case uStreamer fails to compile?
</blockquote></details>

Oh, yeah, that's super annoying.

My recommendation of how to solve this is to:

1. Install Janus on a bare Raspbian system either with [ansible-role-janus-gateway](https://github.com/tiny-pilot/ansible-role-janus-gateway) or by copy/pasting [these commands](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/be5cac0fdd9bb2261ac1c829adcca117dfba60b3/janus_ustreamer_docker/Dockerfile#L3L63).
2. Try to create a symlink to `refcount.h` in the place that uStreamer's make is looking (I *think* `/usr/include/janus/refcount.h`, but I haven't tested it).

It just feels a little dirty to directly tamper with the paths in the Janus source, but we can do that too.
___
*[docs/h264.md, line 74 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8ysH3DHOFRfMWhXUA:-N-8ysH404iGT352TI0m:bf2yx6w) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L74)):*
> ```Markdown
> The client needs to load the following JavaScript libraries:
> 
> - [The WebRTC Adapter library](https://webrtc.github.io/adapter/adapter-8.1.0.js) (`webrtc-adapter.js`, version `8.1.0`)
> ```

If we're loading it from a CDN in the HTML sample, I think we can drop it here since the user doesn't have to do anything special.
___
*[docs/h264.md, line 90 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-9-agR-625-YdKXBJV:-N-9-agR-625-YdKXBJW:b5sa8we) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L90)):*
Can we get rid of passive voice in "has taken place"? Suggest:

>After the JavaScript client and the Janus server complete the JSEP exchange
___
*[docs/h264.md, line 91 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-900MB0UeSP_XYwcXp:-N-900MB0UeSP_XYwcXq:b2lj2to) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L91)):*
> ```Markdown
> 1. Once the H.264 media is available for streaming in the µStreamer plugin, client and server have to negotiate the underlying parameters of the WebRTC session, such as port or codec information. This procedure is called JSEP (JavaScript Session Establishment Protocol), where the server makes a `jsepOffer` to the client, and the client responds with a `jsepAnswer`.
> 1. After the JSEP exchange has taken place, the WebRTC connection is eventually established. The µStreamer plugin automatically begins to deliver the H.264 video stream to the client via WebRTC.
> 1. Once the video data starts to arrive on the client, the `onremotetrack` callback is invoked. The client attaches the received stream track to the `<video>` element. This will render the video stream on the screen.
> ```

Can we just say "stream" instead of "stream track"? We don't explain what a stream track is, but I don't think we need to.

Can we replace passive voice with "the `onremotetrack` callback is invoked". We should say explicitly what component invokes it. It's the Janus JS client, right?
___
*[docs/h264.md, line 100 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-90_RA9zX4r0vVQVw4:-N-90_RA9zX4r0vVQVw5:b-3kai9j) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L100)):*
> ```Markdown
> <head>
>   <meta charset="utf-8">
>   <title>µStreamer H.264 guide</title>
> ```

I liked "demo." The page itself (as rendered in the browser) is more of a demo than a guide.
___
*[docs/h264.md, line 102 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8yzZL97bOgzZuTcuI:-N-8yzZL97bOgzZuTcuJ:b-ew2ko4) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L102)):*
> ```Markdown
>   <title>µStreamer H.264 guide</title>
>   <script src="https://webrtc.github.io/adapter/adapter-8.1.0.js"></script>
>   <script src="janus.js"></script>
> ```

I think it would be helpful to add a comment saying that this is the same janus.js we referenced above that they need to download from github and serve from the same folder as the sample HTML file.
___
*[docs/h264.md, line 128 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-Mzuh40VvOB7o4WnEeB2-r3-128:-N-8zWO3DipHeLscu_Hc:b-xgljfq) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L128)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

In this case, we're not using a reverse proxy like nginx, so this can either be
```javascript
"ws://127.0.0.1:8188/";
// or
"ws://" + window.location.hostname + ":8188/";
```
depending on how the demo html file is accessed.
([source](https://janus.conf.meetecho.com/docs/deploy.html#deplyws))
</blockquote></details>

Oh, nice, I like the `window.location.hostname` idea!
___
*[docs/h264.md, line 189 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-91F9J96rTM_aIHyW-:-N-91F9J96rTM_aIHyW0:bf4ryw9) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L189)):*
> ```Markdown
>             // Attach the received media track to the video element.
>             const stre [...]

2022-04-08 16:43 UTC, mtlynch reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-92GrSEUgbNZ4rAaYz:b-6q0gcd) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Oh, yeah, that's super annoying.

My recommendation of how to solve this is to:

1. Install Janus on a bare Raspbian system either with [ansible-role-janus-gateway](https://github.com/tiny-pilot/ansible-role-janus-gateway) or by copy/pasting [these commands](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/be5cac0fdd9bb2261ac1c829adcca117dfba60b3/janus_ustreamer_docker/Dockerfile#L3L63).
2. Try to create a symlink to `refcount.h` in the place that uStreamer's make is looking (I *think* `/usr/include/janus/refcount.h`, but I haven't tested it).

It just feels a little dirty to directly tamper with the paths in the Janus source, but we can do that too.
</blockquote></details>

Oh, to clarify, this is my suggestion for how @jotaen4tinypilot can test and find a solution to compile the uStreamer plugin on a system with Janus installed. I don't think we should ask the reader to go through that process.

I'm hoping that we can find a one-liner that lets the user compile the Janus plugin if they have Janus on their system. The `sed` solution is fine, but it would be nice if we could find something that's even cleaner, like temporarily adding a symlink and then removing it after the `make`.


<!-- Sent from Reviewable.io -->

2022-04-08 17:18 UTC, jotaen4tinypilot reviewed
> One nit-picky thing that bothers me the how we refer to the uStreamer Janus plugin. 

Good point, I’ve used “µStreamer Janus plugin” now, because that sounds most clear to me. For brevity, it’s sometimes just “plugin”, but I think that should be clear, since there is no other plugin involved. The same applies for “Janus WebRTC server” <> “server”.

> I think the inline code comments help a lot.

:thumbsup:


### Open todos

- [ ] Update the server instructions with uStreamer 5.x.
- [ ] Figure out why we need to clone the media track.
- [ ] Account for the `refcount.h` issue

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-8xvfGCjFA6N8sQIuy:b-u14tdn)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 16 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-87RJ11KBSM1TMTkOy:-N-8j63F1ath5MG4JjHY:bl1iugp) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L16)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

(nit, optional) We're using "server" to refer to both the hardware and software. Which is correct, but might be ambiguous.

Suggestion:
The server starts the Janus WebRTC *service* with the µStreamer plugin.

This might not work everywhere in this document.
</blockquote></details>

I think “Janus WebRTC server” is the most accurate term, which they also use in their own documentation, so I’d like to stick to that if possible. Alternating between “server” and “service” might also create confusion, because then it’s ambiguous whether two separate things are meant.

I realized, that to me the term “The server...” is what I’m not super happy with actually. The video origin doesn’t have to be a (hardware) server at all, but it could really be *any* device with Video4Linux capabilities. Therefore, I’ve changed to “V4L2 device” now. This term is also used in [uStreamers README](https://github.com/pikvm/ustreamer#%C2%B5streamer).

I’ve also slightly adjusted the introduction in that respect.
___
*[docs/h264.md, line 26 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8-3ENE-PtohKcCTLt:-N-90zx513TtJIcgdNaQ:b-42xmgr) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L26)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

If this were a separate blog post, I'd say pin it, but this documentation is meant to live with uStreamer, so it should always work with uStreamer's `master`.

I think we should stick with the `master` branch and drop `WITH_OMX=1`, since that's gone as of uStreamer 5.x.

I don't think we need a make flag to support memory sharing anymore, but we should verify that with the latest uStreamer and Pi kernel (you'll need to run `sudo rpi-update` to get a kernel compatible with uStreamer 5.x).
</blockquote></details>

Okay, I’ll verify this and then adjust the instructions.
___
*[docs/h264.md, line 26 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8wWi19Y9EEy0Rdh3K:-N-935AGCFeEbwqPArGC:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L26)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we link to the specific section with a relative link, like:

```markdown
see the [build instructions](../README.md#building).
```
</blockquote></details>

Done.
___
*[docs/h264.md, line 74 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8ysH3DHOFRfMWhXUA:-N-93NNO3o7AaJnaVTJm:b-mwzh51) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L74)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

If we're loading it from a CDN in the HTML sample, I think we can drop it here since the user doesn't have to do anything special.
</blockquote></details>

My original reasoning with the prerequisite section was to make it a complete list of the dependencies. The user might ignore our demo code and go by the instructions directly, so I think it might be better if the instructions worked “on their own”. (Not married to that, though.)
___
*[docs/h264.md, line 90 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-9-agR-625-YdKXBJV:-N-94fIi7npm42Iy_u-q:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L90)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we get rid of passive voice in "has taken place"? Suggest:

>After the JavaScript client and the Janus server complete the JSEP exchange
</blockquote></details>

Done.
___
*[docs/h264.md, line 91 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-900MB0UeSP_XYwcXp:-N-94v3P4j5RrrDuk1SA:b-896fix) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L91)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we just say "stream" instead of "stream track"? We don't explain what a stream track is, but I don't think we need to.

Can we replace passive voice with "the `onremotetrack` callback is invoked". We should say explicitly what component invokes it. It's the Janus JS client, right?
</blockquote></details>

Done.
___
*[docs/h264.md, line 100 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-90_RA9zX4r0vVQVw4:-N-95Aw116fKPGG3s6CT:bv0jxid) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L100)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I liked "demo." The page itself (as rendered in the browser) is more of a demo than a guide.
</blockquote></details>

True, done.
___
*[docs/h264.md, line 102 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-8yzZL97bOgzZuTcuI:-N-95Ewb9J36eZ0Rvf-t:b9a0utw) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L102)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I think it would be helpful to add a comment saying that this is the same janus.js we referenced above that they need to download from github and serve from the same folder as the sample HTML file.
</blockquote></details>

Done.

Btw., it would be a bit simpler if Github allowed us to hotlink `raw.githubusercontent.com/...` files, but unfortunately it prevents that. (Or if there was a `janus.js` file on a trustworthy CDN.)
___
*[docs/h264.md, line 128 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-Mzuh40VvOB7o4WnEeB2-r3-128:-N-8w2iH9KC2DdnMjJl-:b-rtfi9g) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L128)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Oh, nice, I like the `window.location.hostname` idea!
</blockquote></details>

Done. I’ve changed to:

```js
`ws://${window.location.hostname}:8188/`
```
___
*[docs/h264.md, line 189 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-91F9J96rTM_aIHyW-:-N-97XVa3YVX7fkkK_B3:b-grb7wl) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L189)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we explain why we clone the `mediaStreamTrack` instead of adding it directly?
</blockquote></details>

I need to look into this again. As mentioned [here](https://github.com/tiny-pilot/tinypilot/pull/943#issue-1183964883), I’ve seen this pattern in the [test files of the Janus repo](https://github.com/meetecho/janus-gateway/blob/4110eea4568926dc18642a544718c87118629253/html/streamin [...]

2022-04-12 20:01 UTC, jotaen4tinypilot reviewed
> I think we should stick with the master branch and drop WITH_OMX=1, since that's gone as of uStreamer 5.x.
> 
> I don't think we need a make flag to support memory sharing anymore, but we should verify that with the latest uStreamer and Pi kernel (you'll need to run sudo rpi-update to get a kernel compatible with uStreamer 5.x).

[I’ve dropped the `WITH_OMX` flag now](https://github.com/tiny-pilot/ustreamer/pull/2/commits/a361d86dcbdb4c6e254867087b181754e37d34e3) from the description. I’ve verified via our docker image that [the plugin still works](https://github.com/tiny-pilot/janus-docker/pull/2).

I have also corrected the [instructions to move the `libjanus_ustreamer.so` file](https://github.com/tiny-pilot/ustreamer/pull/2/commits/2e32377e9573439293e3ace4f4fd297a4b2de653), because `./libjanus_ustreamer.so` is only a symlink to `./janus/libjanus_ustreamer.so`.

Then, finally, I [brought back the `{ request: "start" }`](https://github.com/tiny-pilot/ustreamer/pull/2/commits/b21c8dd1cad1697a09fc6726503ef0394fb91216). The plugin functions regardless of whether this request is made or not, but I noticed a `400 Bad Request` response in the logs when it’s not sent. My conclusion is that uStreamer implemented this `start` command only because it seems to be part of the contract of the Janus Plugin API, but not for actual functional reasons.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-Tl3ea1mijyY3LzDLm:bhjoz5a)* status: 0 of 1 LGTMs obtained

___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-Ti424EJM01zQg0O54:b-lii1dr) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Oh, to clarify, this is my suggestion for how @jotaen4tinypilot can test and find a solution to compile the uStreamer plugin on a system with Janus installed. I don't think we should ask the reader to go through that process.

I'm hoping that we can find a one-liner that lets the user compile the Janus plugin if they have Janus on their system. The `sed` solution is fine, but it would be nice if we could find something that's even cleaner, like temporarily adding a symlink and then removing it after the `make`.
</blockquote></details>

Only symlinking `refcount.h` is not enough, unfortunately, because `refcount.h` [includes `mutex.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/refcount.h#L61), which [includes `debug.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/mutex.h#L16), which [includes `log.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/debug.h#L16) (etc. etc.) and they all use local includes. The only other option I would see is to copy or move all the header files into the `plugins` directory.

[This ustreamer issue](https://github.com/pikvm/ustreamer/issues/134) is the only instance where I find this problem mentioned. My C/C++ days are long ago, but it seems odd to me why the path would be incorrect in the first place. This also isn’t specific to the [`plugins.h` header](https://github.com/meetecho/janus-gateway/blob/master/src/plugins/plugin.h), but for [other header files as well](https://github.com/meetecho/janus-gateway/blob/e277486a3ce4276d23ebcd5842e0c58a1ae14b4f/src/plugins/janus_duktape_data.h#L32-L40). But: it’s not consistent, [in a sibling directory, for example](https://github.com/meetecho/janus-gateway/blob/e277486a3ce4276d23ebcd5842e0c58a1ae14b4f/src/loggers/logger.h#L83), they use the “correct” path.

The compilation procedure in our Dockerfile seems in line with [their README](https://github.com/meetecho/janus-gateway/blob/master/README.md#compile). The only other solution that I can think of is somehow adding the parent directory to the pre-processor search path, but I didn’t find an option in the make files to achieve that. (However, I haven’t spent a ton of time on this.)

If we wanted to clarify this, I suppose it’s best to ask about it [in their Google Groups](https://groups.google.com/g/meetecho-janus).
___
*[docs/h264.md, line 189 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-91F9J96rTM_aIHyW-:-N-TkBwD6mIOcq3l6pmV:b-5y6s2q) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L189)):*
<details><summary><i>Previously, jotaen4tinypilot wrote…</i></summary><blockquote>

I need to look into this again. As mentioned [here](https://github.com/tiny-pilot/tinypilot/pull/943#issue-1183964883), I’ve seen this pattern in the [test files of the Janus repo](https://github.com/meetecho/janus-gateway/blob/4110eea4568926dc18642a544718c87118629253/html/streamingtest.js#L249-L250), so I had just done it the same way.

[`MediaStreamTrack.clone`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/clone) creates an identical copy of the stream, but with a distinct [`id` property](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/id). I actually don’t know why this might be important (or not), but it would probably be good to understand that.
</blockquote></details>

After doing some searching, the most reasonable explanation I ended up with is that cloning is done as a precaution or best-practice. One peculiarity of media streams is that there is a global register for them, which can be queried via [`MediaStream.getById`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/getTrackById). My interpretation is that without cloning, another piece of code could get a handle on the track object via the original id. This shouldn’t be a concern for us, but it probably doesn’t harm to clone anyways.


<!-- Sent from Reviewable.io -->

2022-04-12 21:12 UTC, mtlynch reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

We just need to document the `refcount.h` fix.

I'll want to do an editing pass once we merge this in to adjust small wording things, but I think this is ready to check in.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-UbaO20zAeKhqM1xtq:bmnz92s)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-Ub2F83IO-GLZZkiVY:b-4yzg26) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
<details><summary><i>Previously, jotaen4tinypilot wrote…</i></summary><blockquote>

Only symlinking `refcount.h` is not enough, unfortunately, because `refcount.h` [includes `mutex.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/refcount.h#L61), which [includes `debug.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/mutex.h#L16), which [includes `log.h`](https://github.com/meetecho/janus-gateway/blob/cc3cd741460e6c6b93c720d1805a98d350a489c9/src/debug.h#L16) (etc. etc.) and they all use local includes. The only other option I would see is to copy or move all the header files into the `plugins` directory.

[This ustreamer issue](https://github.com/pikvm/ustreamer/issues/134) is the only instance where I find this problem mentioned. My C/C++ days are long ago, but it seems odd to me why the path would be incorrect in the first place. This also isn’t specific to the [`plugins.h` header](https://github.com/meetecho/janus-gateway/blob/master/src/plugins/plugin.h), but for [other header files as well](https://github.com/meetecho/janus-gateway/blob/e277486a3ce4276d23ebcd5842e0c58a1ae14b4f/src/plugins/janus_duktape_data.h#L32-L40). But: it’s not consistent, [in a sibling directory, for example](https://github.com/meetecho/janus-gateway/blob/e277486a3ce4276d23ebcd5842e0c58a1ae14b4f/src/loggers/logger.h#L83), they use the “correct” path.

The compilation procedure in our Dockerfile seems in line with [their README](https://github.com/meetecho/janus-gateway/blob/master/README.md#compile). The only other solution that I can think of is somehow adding the parent directory to the pre-processor search path, but I didn’t find an option in the make files to achieve that. (However, I haven’t spent a ton of time on this.)

If we wanted to clarify this, I suppose it’s best to ask about it [in their Google Groups](https://groups.google.com/g/meetecho-janus).
</blockquote></details>

Oh, too bad that there isn't an easier fix. Can we document the workaround under `Installation`? Otherwise, it won't really compile like we say, right?


<!-- Sent from Reviewable.io -->

2022-04-13 07:05 UTC, jotaen4tinypilot reviewed
Depending on whether you want to do the editing on this branch or on a new one, feel free to merge. From my side it’s good to go.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-:-N-WiV2D9MXG3bSkbm73:b-2qhi66)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[docs/h264.md, line 36 at r3](https://reviewable.io/reviews/tiny-pilot/ustreamer/2#-N-89kXP1vmniAj_8hgI:-N-WiqAr8KMhW9ZiUQVI:bttaze2) ([raw file](https://github.com/tiny-pilot/ustreamer/blob/4daf17ce6ae7bda8ce2451f80fb7163ccc114588/docs/h264.md#L36)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Oh, too bad that there isn't an easier fix. Can we document the workaround under `Installation`? Otherwise, it won't really compile like we say, right?
</blockquote></details>

[I’ve put it under “Prerequisites”](https://github.com/tiny-pilot/ustreamer/pull/2/commits/6059f9516c86bc8b572082ed872f1d97ec89b04e). I thought that was a slightly better fit, because actually the compilation error is due to the include headers not having been made available correctly beforehand.


<!-- Sent from Reviewable.io -->

2022-04-13 10:31 UTC, merged